site_name: Asahi Linux Documentation
site_url: https://asahilinux.org/docs/

repo_url: https://github.com/AsahiLinux/docs
repo_name: AsahiLinux/docs

nav:
  - Home: index.md
  - Feature Support:
    - Overview: platform/feature-support/overview.md
    - M1 Series Feature Support: platform/feature-support/m1.md
    - M2 Series Feature Support: platform/feature-support/m2.md
    - M3 Series Feature Support: platform/feature-support/m3.md
    - M4 Series Feature Support: platform/feature-support/m4.md
  - Project related:
    - Glossary: project/glossary.md
    - FAQ: project/faq.md
    - When will Asahi Linux be done?: project/when-will-asahi-be-done.md
    - References: project/references.md
    - Asahi Linux Board: project/board/asahi-board.md
  - Platform documentation:
    - Apple Silicon Subsystems: platform/subsystems.md
    - Apple Platform Security Crash Course: platform/security.md
    - Devices: hw/devices/device-list.md
    - Codenames: hw/soc/soc-codenames.md
    - Display Controllers: hw/soc/display-controllers.md
  - For users:
    - Fedora Asahi Remix Documentation <i class="fa-solid fa-arrow-up-right-from-square"></i>: https://docs.fedoraproject.org/en-US/fedora-asahi-remix/
    - Broken Software: sw/broken-software.md
  - For developers:
    - Yaks in need of shaving (HELP WANTED!): project/help-wanted.md
    - Tethered Boot Setup (For Developers): sw/tethered-boot.md
    - m1n1:User Guide Boot loader: sw/m1n1-user-guide.md
    - Hypervisor: sw/m1n1-hypervisor.md
    - U-Boot: sw/u-boot.md
    - Devicetree bindings: sw/devicetree-bindings.md
    - Open OS ecosystem on Apple Silicon Macs: platform/open-os-interop.md
    - Userspace Audio Stack: sw/audio-userspace.md
  - For distributions/OSes:
    - Distro guidelines: alt/policy.md

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    - media: "(prefers-color-scheme)"
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      primary: custom
      accent: custom
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      primary: custom
      accent: custom
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - navigation.top
    - toc.integrate
  custom_dir: overrides

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - toc:
      baselevel: 4
      permalink: true
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - social:
      cards_layout_options:
        background_color: '#F4EAEA'
        color: '#2C2C2C'
