name: Pages
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/asahilinux/mkdocs-asahi
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Configure Git Credentials
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          # This is needed for the deployment to work
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Build
        if: github.event_name == 'pull_request'
        run: mkdocs build
      - name: Build and deploy to GitHub Pages
        if: github.event_name != 'pull_request'
        run: mkdocs gh-deploy --force
